name: Publish to Visual Studio Marketplace

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish to VS Marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set version from branch name
        uses: ./.github/actions/set-version

      - name: Build VSIX package
        uses: ./.github/actions/build-vsix
        with:
          version: ${{ env.VERSION }}

      - name: Publish to VS Marketplace
        run: make publish-marketplace
        env:
          VERSION: ${{ env.VERSION }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
